version: '3'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer/data:/data

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    # network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
      - UMASK=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ./volumes/deluge/config:/config
      - ./downloads:/downloads
    ports:
      - 8112:8112
      - 58846:58846
      - 58946:58946

  jellyfin:
    image: ghcr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
      - UMASK_SET=<022> #optional
    volumes:
      - ./volumes/jellyfin/config:/config
      - ./media/tvshows:/data/tvshows
      - ./media/movies:/data/movies
      #- /opt/vc/lib:/opt/vc/lib #optional
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    #devices:
      #- /dev/dri:/dev/dri #optional
      #- /dev/vcsm:/dev/vcsm #optional
      #- /dev/vchiq:/dev/vchiq #optional
      #- /dev/video10:/dev/video10 #optional
      #- /dev/video11:/dev/video11 #optional
      #- /dev/video12:/dev/video12 #optional

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
      - AUTO_UPDATE=true #optional
      # - RUN_OPTS=<run options here> #optional
    volumes:
      - ./volumes/jackett/config:/config
      - ./downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
      - UMASK_SET=022 #optional
    volumes:
      - ./volumes/sonarr/data:/config
      - ./media/tvshows:/tv
      - ./downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Africa/Johannesburg
      - UMASK=022 #optional
    volumes:
      - ./volumes/radarr/config:/config
      - ./media/movies:/movies
      - ./downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  overseerr:
    image: ghcr.io/linuxserver/overseerr
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
    volumes:
      - /volumes/overseerr/config:/config
    ports:
      - 5055:5055
    restart: unless-stopped